def dockerImage
pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
        AWS_DEFAULT_REGION = 'ap-southeast-1'
        IMAGE_TAG = "v${env.BUILD_NUMBER}"
        IMAGE_NAME = "ctchin1981/hello-world-java:${IMAGE_TAG}"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                echo "IMAGE_NAME - ${IMAGE_NAME}"
                script {
                    // Check if Maven Central is reachable
                    def canReachMaven = sh(
                    //     script: "curl -s --connect-timeout 3 https://repo.maven.apache.org/maven2 > /dev/null && echo true || echo false",
                    //     returnStdout: true
                    // ).trim()

                    // def proxyArgs = canReachMaven == 'true' ? "" :
                    //     "--build-arg HTTP_PROXY=http.docker.internal:3128 --build-arg HTTPS_PROXY=http.docker.internal:3128"

                    def bypass_internal_dns = "--dns=8.8.8.8 --dns=1.1.1.1"

                    dockerImage = docker.build(IMAGE_NAME, "${bypass_internal_dns} hello-world-java")
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('', 'myDockerHub') {
                        dockerImage.push()
                    }
                }
            }
        }

        stage('Generate container-definitions-java.json') {
            steps {
                writeFile file: 'container-definitions-java.json', text: """
                [
                    {
                        "name": "java-app",
                        "image": "${IMAGE_NAME}",
                        "portMappings": [
                            {
                            "containerPort": 5000,
                            "protocol": "tcp"
                            }
                        ],
                        "essential": true
                    }
                ]
                """
            }
        }

        stage('Register ECS Task Definition') {
            steps {
                sh """
                    aws ecs register-task-definition \
                    --family java-app-task \
                    --network-mode awsvpc \
                    --requires-compatibilities FARGATE \
                    --cpu "256" \
                    --memory "512" \
                    --execution-role-arn arn:aws:iam::701909704491:role/ecsTaskExecutionRole \
                    --container-definitions file://container-definitions-java.json
                """
            }
        }

        stage('Update ECS Service') {
            steps {
                sh """
                    aws ecs update-service \
                    --cluster hello-world-cluster \
                    --service java-app-service \
                    --task-definition java-app-task
                """
            }
        }
    }
}